export { Navbar } from './Navbar'
export { HeroSection } from './HeroSection'
export { Footer } from './Footer'
export { Layout } from './Layout'
// export { FeaturesSection } from './FeaturesSection'
export { HowItWorksSection } from './HowItWorksSection'
export { TestimonialsSection } from './TestimonialsSection'
export { CallToActionSection } from './CallToActionSection'
// export { DemoSection } from './DemoSection'
export { PricingSection } from './PricingSection'